<a href="https://colab.research.google.com/github/SaRDoRBeK0104/Ismoilov_AI-Datascience/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Creating arrays

In [ ]:
import numpy as np

In [3]:
data1 = [3.2,12,1,6,15.2]   # list
arr1 = np.array(data1)  # array1

In [5]:
arr1

array([ 3.2, 12. ,  1. ,  6. , 15.2])

In [6]:
data2 = [12,3,2.2,7]  # tuple
arr2 = np.array(data2)

Massiv o'lchami 
**ndim**

In [7]:
arr1.ndim

1

In [8]:
arr2.ndim

1

**Ikki va undan katta o'lchamli massivlar**

In [9]:
data3 = [[3,2,1,0],[7,6,5,4]]  #nested list
arr3 = np.array(data3)

In [10]:
arr3

array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

In [11]:
data3

[[3, 2, 1, 0], [7, 6, 5, 4]]

In [12]:
arr3.ndim

2

**3 o'lchovli massiv**

In [13]:
data4 = [[2,4,5,4],[23,15,10,1],[4,5,14,19]]
arr4 = np.array(data4)

In [15]:
data4

[[2, 4, 5, 4], [23, 15, 10, 1], [4, 5, 14, 19]]

In [16]:
arr4

array([[ 2,  4,  5,  4],
       [23, 15, 10,  1],
       [ 4,  5, 14, 19]])

In [17]:
arr4.ndim

2

In [22]:
data5 = np.arange(27).reshape(3,3,3)

In [23]:
data5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
data5.ndim

3

**Qo'lbola**

In [27]:
data6 = [[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]
arr6 = np.array(data6)

In [28]:
arr6

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [29]:
arr6.ndim

3

***shape va size metodlari***

In [30]:
arr6.shape  # (blok, ustun, qator)

(2, 3, 3)

In [31]:
arr4.shape  # (qator, ustun)

(3, 4)